<?php

$person_labels = array(
    'name' => _x('Personen', 'Post Type General Name', FAU_PERSON_TEXTDOMAIN),
    'singular_name' => _x('Person', 'Post Type Singular Name', FAU_PERSON_TEXTDOMAIN),
    'menu_name' => __('Personen', FAU_PERSON_TEXTDOMAIN),
    'parent_item_colon' => __('Übergeordnete Person', FAU_PERSON_TEXTDOMAIN),
    'all_items' => __('Alle Personen', FAU_PERSON_TEXTDOMAIN),
    'view_item' => __('Person ansehen', FAU_PERSON_TEXTDOMAIN),
    'add_new_item' => __('Person hinzufügen', FAU_PERSON_TEXTDOMAIN),
    'add_new' => __('Neue Person', FAU_PERSON_TEXTDOMAIN),
    'edit_item' => __('Person bearbeiten', FAU_PERSON_TEXTDOMAIN),
    'update_item' => __('Person aktualisieren', FAU_PERSON_TEXTDOMAIN),
    'search_items' => __('Personen suchen', FAU_PERSON_TEXTDOMAIN),
    'not_found' => __('Keine Personen gefunden', FAU_PERSON_TEXTDOMAIN),
    'not_found_in_trash' => __('Keine Personen in Papierkorb gefunden', FAU_PERSON_TEXTDOMAIN),
);
$person_rewrite = array(
    'slug' => 'person',
    'with_front' => true,
    'pages' => true,
    'feeds' => true,
);
$person_args = array(
    'label' => __('person', FAU_PERSON_TEXTDOMAIN),
    'description' => __('Personeninformationen', FAU_PERSON_TEXTDOMAIN),
    'labels' => $person_labels,
    'supports' => array('title', 'thumbnail'),
    'taxonomies' => array('persons_category'),
    'hierarchical' => false,
    'public' => true,
    'show_ui' => true,
    'show_in_menu' => true,
    'show_in_nav_menus' => false,
    'show_in_admin_bar' => true,
    'menu_position' => 5,
    'menu_icon' => 'dashicons-businessman',
    'can_export' => true,
    'has_archive' => true,
    'exclude_from_search' => false,
    'publicly_queryable' => true,
    'query_var' => 'person',
    'rewrite' => $person_rewrite,
    'capability_type' => 'person',
    'capabilities' => array(
        'edit_post' => 'edit_person',
        'read_post' => 'read_person',
        'delete_post' => 'delete_person',
        'edit_posts' => 'edit_persons',
        'edit_others_posts' => 'edit_others_persons',
        'publish_posts' => 'publish_persons',
        'read_private_posts' => 'read_private_persons',
        'delete_posts' => 'delete_persons',
        'delete_private_posts' => 'delete_private_persons',
        'delete_published_posts' => 'delete_published_persons',
        'delete_others_posts' => 'delete_others_persons',
        'edit_private_posts' => 'edit_private_persons',
        'edit_published_posts' => 'edit_published_persons'
    ),
    'map_meta_cap' => true
);

$person_titel_options = array(
    'Dr.' => 'Doktor',
    'Prof.' => 'Professor',
    'Dipl.' => 'Diplom',
    'B.A.' => 'Bakkalaureus',
    'M.A.' => 'Magister Artium',
);

/* möglich bei type: text, textarea, checkbox, select, image, title, headline (für Zwischenüberschriften) */
$person_fields = array(
    // Zuordnung - fau_person_orga
    '_person_institution' => array(
        'default' => 'false',
        'title' => __('Institution/Abteilung', FAU_PERSON_TEXTDOMAIN),
        'description' => 'Geben Sie hier die Institution ein.',
        'type' => 'text',
        'meta_box' => 'fau_person_orga',
        'location' => 'person'),
    '_person_position' => array(
        'default' => 'false',
        'title' => __('Position/Funktion', FAU_PERSON_TEXTDOMAIN),
        'description' => '',
        'type' => 'text',
        'meta_box' => 'fau_person_orga',
        'location' => 'person'),
    '_person_link' => array(
        'default' => 'false',
        'title' => __('"Mehr"-Link führt zur Seite ...', FAU_PERSON_TEXTDOMAIN),
        'description' => 'Bitte vollständigen Permalink der Zielseite angeben',
        'type' => 'text',
        'meta_box' => 'fau_person_orga',
        'location' => 'person'),
    // Kontaktinformation - fau_person_info
    '_person_typ' => array(
        'default' => 'false',
        'title' => __('Typ des Eintrags', FAU_PERSON_TEXTDOMAIN),
        'description' => '',
        'type' => 'select',
        'options' => array('realmale' => __('Männliche Person', FAU_PERSON_TEXTDOMAIN),
            'realfemale' => __('Weibliche Person', FAU_PERSON_TEXTDOMAIN),
            'pseudo' => __('Pseudonym', FAU_PERSON_TEXTDOMAIN),
            'einrichtung' => __('Einrichtung', FAU_PERSON_TEXTDOMAIN)
            ),
        'meta_box' => 'fau_person_typ',
        'location' => 'person'),
    '_person_titel' => array(
        'default' => 'false',
        'title' => __('Titel (Präfix)', FAU_PERSON_TEXTDOMAIN),
        'description' => '',
        'type' => 'select',
        'options' => $person_titel_options,
        'meta_box' => 'fau_person_info',
        'location' => 'person'),
    '_person_vorname' => array(
        'default' => 'false',
        'title' => __('Vorname', FAU_PERSON_TEXTDOMAIN),
        'description' => '',
        'type' => 'text',
        'meta_box' => 'fau_person_info',
        'location' => 'person'),
    '_person_nachname' => array(
        'default' => 'false',
        'title' => __('Nachname', FAU_PERSON_TEXTDOMAIN),
        'description' => '',
        'type' => 'text',
        'meta_box' => 'fau_person_info',
        'location' => 'person'),
    '_person_pseudo' => array(
        'default' => 'false',
        'title' => __('Bezeichnung (oder Pseudonym)', FAU_PERSON_TEXTDOMAIN),
        'description' => '',
        'type' => 'text',
        'meta_box' => 'fau_person_info',
        'location' => 'person'),
    '_person_abschluss' => array(
        'default' => 'false',
        'title' => __('Abschluss (Suffix)', FAU_PERSON_TEXTDOMAIN),
        'description' => '',
        'type' => 'text',
        'meta_box' => 'fau_person_info',
        'location' => 'person'),
    '_person_strasse' => array(
        'default' => 'false',
        'title' => __('Straße und Hausnummer', FAU_PERSON_TEXTDOMAIN),
        'description' => '',
        'type' => 'text',
        'meta_box' => 'fau_person_info',
        'location' => 'person'),
    '_person_plz' => array(
        'default' => 'false',
        'title' => __('Postleitzahl', FAU_PERSON_TEXTDOMAIN),
        'description' => '',
        'type' => 'text',
        'meta_box' => 'fau_person_info',
        'location' => 'person'),
    '_person_ort' => array(
        'default' => 'false',
        'title' => __('Ort', FAU_PERSON_TEXTDOMAIN),
        'description' => '',
        'type' => 'text',
        'meta_box' => 'fau_person_info',
        'location' => 'person'),
    '_person_land' => array(
        'default' => 'false',
        'title' => __('Land', FAU_PERSON_TEXTDOMAIN),
        'description' => '',
        'type' => 'text',
        'meta_box' => 'fau_person_info',
        'location' => 'person'),
    '_person_raum' => array(
        'default' => 'false',
        'title' => __('Raum', FAU_PERSON_TEXTDOMAIN),
        'description' => '',
        'type' => 'text',
        'meta_box' => 'fau_person_info',
        'location' => 'person'),
    '_person_telefon' => array(
        'default' => 'false',
        'title' => __('Telefon', FAU_PERSON_TEXTDOMAIN),
        'description' => '',
        'type' => 'text',
        'meta_box' => 'fau_person_info',
        'location' => 'person'),
    '_person_telefax' => array(
        'default' => 'false',
        'title' => __('Telefax', FAU_PERSON_TEXTDOMAIN),
        'description' => '',
        'type' => 'text',
        'meta_box' => 'fau_person_info',
        'location' => 'person'),
    // Social Media - fau_person_social_media
    '_person_email' => array(
        'default' => 'false',
        'title' => __('E-Mail', FAU_PERSON_TEXTDOMAIN),
        'description' => '',
        'type' => 'text',
        'meta_box' => 'fau_person_social_media',
        'location' => 'person'),
    '_person_url' => array(
        'default' => 'false',
        'title' => __('Webseite', FAU_PERSON_TEXTDOMAIN),
        'description' => '',
        'type' => 'url',
        'meta_box' => 'fau_person_social_media',
        'location' => 'person'),
    // Weitere Informationen - fau_person_adds
    '_person_freitext' => array(
        'default' => 'false',
        'title' => __('Freitext', FAU_PERSON_TEXTDOMAIN),
        'description' => '',
        'type' => 'textarea',
        'meta_box' => 'fau_person_adds',
        'location' => 'person'),
    '_person_sprechzeiten' => array(
        'default' => 'false',
        'title' => __('Sprechzeiten', FAU_PERSON_TEXTDOMAIN),
        'description' => '',
        'type' => 'text',
        'meta_box' => 'fau_person_adds',
        'location' => 'person'),
    '_person_pubs' => array(
        'default' => 'false',
        'title' => __('Publikationen', FAU_PERSON_TEXTDOMAIN),
        'description' => '',
        'type' => 'text',
        'meta_box' => 'fau_person_adds',
        'location' => 'person')
    // Synchronisierung mit externen Daten - fau_person_sync ab hier

);



